/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPage;

import Admin.*;
import java.awt.Color;
import internalpage.*;
import internalpage.UserdashboardPage;
import internalpage.ProjectPage;
import internalpage.TaskPage;
/**
 *
 * @author SCC-COLLEGE
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form Admindashboard
     */
    public mainPage() {
        initComponents();
    }
    
    Color navcolor = new Color(204,255,204);
    Color headcolor = new Color(153,255,153);
    Color bodycolor = new Color(204,255,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        projectlist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reportpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tasklist = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        maindesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        navbar.setBackground(new java.awt.Color(204, 255, 204));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        projectlist.setBackground(new java.awt.Color(204, 255, 204));
        projectlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectlistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectlistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectlistMouseExited(evt);
            }
        });
        projectlist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROJECTS LIST");
        projectlist.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        navbar.add(projectlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 40));

        userpanel.setBackground(new java.awt.Color(204, 255, 204));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpanelMouseExited(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER PAGE");
        userpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        navbar.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        reportpanel.setBackground(new java.awt.Color(204, 255, 204));
        reportpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportpanelMouseExited(evt);
            }
        });
        reportpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORTS");
        reportpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        navbar.add(reportpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 160, 40));

        tasklist.setBackground(new java.awt.Color(204, 255, 204));
        tasklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasklistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tasklistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tasklistMouseExited(evt);
            }
        });
        tasklist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TASK LIST");
        tasklist.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        navbar.add(tasklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, 40));

        dashpanel.setBackground(new java.awt.Color(204, 255, 204));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpanelMouseExited(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DASHBOARD");
        dashpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, -1));

        navbar.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 40));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 160, 460);

        header.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(header);
        header.setBounds(160, 0, 760, 40);

        maindesktop.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop);
        maindesktop.setBounds(160, 40, 760, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectlistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectlistMouseEntered
        projectlist.setBackground(bodycolor);
    }//GEN-LAST:event_projectlistMouseEntered

    private void projectlistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectlistMouseExited
        projectlist.setBackground(navcolor);
    }//GEN-LAST:event_projectlistMouseExited

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
        UserdashboardPage up = new UserdashboardPage();
        maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_userpanelMouseClicked

    private void userpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseEntered
        userpanel.setBackground(bodycolor);
    }//GEN-LAST:event_userpanelMouseEntered

    private void userpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseExited
        userpanel.setBackground(navcolor);
    }//GEN-LAST:event_userpanelMouseExited

    private void reportpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpanelMouseEntered
        reportpanel.setBackground(bodycolor);
    }//GEN-LAST:event_reportpanelMouseEntered

    private void reportpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpanelMouseExited
        reportpanel.setBackground(navcolor);
    }//GEN-LAST:event_reportpanelMouseExited

    private void projectlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectlistMouseClicked
        ProjectPage Pg = new ProjectPage();
        maindesktop.add(Pg).setVisible(true);
    }//GEN-LAST:event_projectlistMouseClicked

    private void tasklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklistMouseClicked
        TaskPage tp = new TaskPage();
         maindesktop.add(tp).setVisible(true);
    }//GEN-LAST:event_tasklistMouseClicked

    private void tasklistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklistMouseEntered
        tasklist.setBackground(bodycolor);
    }//GEN-LAST:event_tasklistMouseEntered

    private void tasklistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklistMouseExited
        tasklist.setBackground(navcolor);
    }//GEN-LAST:event_tasklistMouseExited

    private void dashpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseClicked
        AdmindashboardPage Adbp = new AdmindashboardPage();
        maindesktop.add(Adbp).setVisible(true);
    }//GEN-LAST:event_dashpanelMouseClicked

    private void dashpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseEntered
        dashpanel.setBackground(bodycolor);
    }//GEN-LAST:event_dashpanelMouseEntered

    private void dashpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseExited
        dashpanel.setBackground(navcolor);
    }//GEN-LAST:event_dashpanelMouseExited

    private void reportpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportpanelMouseClicked
        reportpanel.setBackground(headcolor);
    }//GEN-LAST:event_reportpanelMouseClicked

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashpanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel projectlist;
    private javax.swing.JPanel reportpanel;
    private javax.swing.JPanel tasklist;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
